### ISSUE TITLE
Updating to WordPress 6.2

### ISSUE THREAD

**Issue by Olein-jp** [Olein-jp/cormorant#9]
## Check from [WordPress 6.2 Field Guide](https://make.wordpress.org/core/2023/03/09/wordpress-6-2-field-guide/)

- [x] [Shadows in Global Styles with WordPress 6.2](https://make.wordpress.org/core/2023/03/07/shadows-in-global-styles-with-wordpress-6-2/)
- [x] [Sticky position block support](https://make.wordpress.org/core/2023/03/07/sticky-position-block-support/)
- [x] [Minimum height dimensions block support](https://make.wordpress.org/core/2023/03/06/minimum-height-dimensions-block-support/)
- [x] [Customize settings for any block in WordPress 6.2](https://make.wordpress.org/core/2023/02/28/custom-settings-wordpress-6-2/)
- [x] [Update to content only editing filter namespace](https://make.wordpress.org/core/2022/12/09/update-to-content-only-editing-filter-namespace/)
- [x] [Patterns API expanded to include template_types property](https://make.wordpress.org/core/2023/03/07/patterns-api-expanded-to-include-template_types-property/)
- [x] [Miscellaneous Editor changes in WordPress 6.2](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/)
- [x] [Google Fonts are included locally in bundled themes](https://make.wordpress.org/core/2023/03/06/google-fonts-are-included-locally-in-bundled-themes/)

## TODO
- [x] Change preset color name foreground to base, background to contrast
- [x] Change fluid typography changing scale for fitting Japanese Fonts
- [x] Re-consider spacing scales
- [x] Checking all block patterns
  - [x] Call to action
  - [x] Hero
  - [x] Profile
  - [x] Team
  - [x] Testimonial
  - [x] Banner
  - [x] FAQ
  - [x] Query
  - [x] Page
  - [x] Header
  - [x] Footer
  - [x] Gallery
  - [x] Price
- [x] Checking all templates
  - [x] 404
  - [x] Archive
  - [x] Date
  - [x] Front page
  - [x] Home
  - [x] Index
  - [x] Page
  - [x] Search
  - [x] Single
  - [x] Blank
- [x] Checking all template parts
  - [x] Footer
  - [x] Header
  - [x] Check template parts can replace

**Comment by Olein-jp** [comment]
Reference for font size scale: https://standard.shiftbrain.com/blog/harmonious-proportions-in-type-sizes
